[package]
name = "ch4-mio-webserver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.45"
env_logger = "0.9.0"
log = "0.4.14"
mio = "0.6.11"
regex = "1.5.4"
